### ISSUE TITLE
Inheriting GTK::Grid to class with custom .new

### ISSUE THREAD

**Issue by hythm7** [Xliff/p6-GtkPlus#26] opened 2019-01-11 21:07 UTC
I get "'GTK_IS_GRID (grid)' failed" for below code, it works fine if I removed .new method

```
use GTK::Application;
use GTK::Box;
use GTK::Button;
use GTK::Grid;

class G { 
  also is GTK::Grid;
  
  method new () {
    self.bless;
  }
  
  submethod BUILD() {
    self.attach: GTK::Button.new_with_label('aaa'), 0, 0, 1, 1;
  }
}

my $app = GTK::Application.new(
  title  => 'org.genex.test.widget',
  width  => 400,
  height => 400
);

$app.activate.tap({
  CATCH { default { .message.say; $app.exit } }
  
  my GTK::Button $exit .= new_with_label: <exit>;
  $exit.clicked.tap: { $app.exit  };
  my G $grid .= new;
  
  my $box = GTK::Box.new-vbox(4);

  $box.pack_start($grid, False, True, 0);
  $box.pack_start($exit, False, True, 0);

  $app.window.add: $box;
  $app.show_all;
});

$app.run;
```

**Comment by Xliff** [comment] 2019-01-11 21:28
There are a lot of issues with inheritance that has yet to be figured out. For one thing, you _aren't_ setting up things correctly with your new method, since it doesn't do a lot of the initialization found in GTK::Grid. About the easiest thing you can do is use nextwith, ala:

```perl6
class G { 
  also is GTK::Grid;
  
  method new () {
    my $o = nextwith;
    # ... More code here, that uses $o to reference the new object.
    # ...
    # MUST return $o at the end!
    $o;
  }
  
  submethod BUILD() {
    self.attach: GTK::Button.new_with_label('aaa'), 0, 0, 1, 1;
  }
}
```

I've just tried it on your example, and it seems to work just fine.

**Comment by hythm7** [comment] 2019-01-11 21:42
That worked. Thank you!

**Comment by hythm7** [comment] 2019-01-12 09:33
nextwith worked with the above example, but when apply it for the code below it complains about BUILD method (Required named parameter 'sym' not passed), by any chance is there a workaround for that?

```
method new (IO::Path :$filename!) {
  my $file = slurp $filename;
  return Nil unless [==] (.chars for $file.lines);

  my $row-count = $file.lines.elems;
  my $col-count = $file.lines[0].chars;

  my @sym = $file.comb: /\N/;
  self.bless(:@sym, :$row-count, :$col-count);
}

submethod BUILD (
  :@sym!,
  :$row-count!,
  :$col-count!,
) {
....
}
```
Complete code is here: https://github.com/hythm7/Z/blob/master/lib/Z/Cipher.pm#L50

**Comment by Xliff** [comment] 2019-01-12 14:33
I don't see any use of nextwith in that code. Can you please restore it to the original, so I can reproduce?

**Comment by hythm7** [comment] 2019-01-12 18:01
I have updated the code once I put nextwith (anywhere in .new) it throws "Required named parameter 'sym' not passed";
```
method new (IO::Path :$filename!) {
  my $o = nextwith;
  $o;
}

submethod BUILD (
  :@sym!,
  :$row-count!,
  :$col-count!,
) {
....
}
```
I have updated the code in repository as well, here https://github.com/hythm7/Z/blob/master/lib/Z/Cipher.pm#L51
to reproduce: I run 'bin/z.p6' and click on the File Chooser Button, then select 'cipher/test'.

**Comment by Xliff** [comment] 2019-01-12 18:55
I just added a PR. See if that helps!

I will reopen this issue if you want to discuss this, further.

For the record: Subclassing widgets is _not_ recommended unless you are trying to add functionality to the widget. There is a lot of stuff involved, and I don't see anything like that in your current implementation of Z::Cipher. The changes in the PR allow you to use a GTK::Grid attached to the object, although there are still some tweaks to be made to make it usable.

**Comment by hythm7** [comment] 2019-01-13 07:21
I really appreciate your help, Thank you Xliff.

**Comment by Xliff** [comment] 2019-01-13 15:22
Any time! Please close the issue (or let me know and I'll close it) if there's nothing else.

**Closed as completed** 2019-01-13 15:28 UTC
